config/routes.rb
Rails.application.routes.draw do
  get 'invoice/index'
  get 'invoice/create'
  get 'delete/index'
  get 'delete/create'
  root 'home#index'
  
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  

  resources :answer_questions, only: [ :create ]
  
  resources :quiz, only: [ :show ] do
    resources :categories, only: [ :show ]
    resources :questions, only: [ :show ]
  end

  get '/quiz_prepare/:id', to: 'quiz#prepare', as: 'quiz_prepare'
  
  resources :results, only: [ :index, :show ]
  resources :practice, only: [ :index ]

  namespace :practice do
    resources :contact, only: [ :index ]
    resources :domains, only: [ :index, :create ]
    resources :nameserver, only: [ :index, :create ]
    resources :transfer, only: [ :index, :create ]
    resources :renew, only: [ :index, :create ]
    resources :change_registrant_email, only: [ :index, :create ]
    resources :change_registrant_verification, only: [ :index, :create ]
    resources :delete, only: [ :index, :create ]
    resources :invoice, only: [ :index, :create ]
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
require_relative '../services/api_connector.rb'


class HomeController < ApplicationController
  skip_before_action :authenticate_user!, :only => [:index]

  def index
    @quizzes = Quiz.where(user: current_user)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<% if user_signed_in? %>

	<main class="w-full place-content-center flex justify-evenly flex-wrap content-center mt-10 mb-48 pt-12 h-4/5">

		<% if @quizzes.any? %>

		<% current_user.quizzes.order(created_at: :desc).each do |quiz| %>
			<div class="rounded-lg flex-initial my-6" style="box-shadow: rgba(255, 255, 255, 0.1) 0px 1px 1px 0px inset, rgba(50, 50, 93, 0.25) 0px 50px 100px -20px, rgba(0, 0, 0, 0.3) 0px 30px 60px -30px;">
					<div class="bg-gray-100 rounded-lg w-96">

							<div class="px-10 py-6 text-center">
									<div class="mb-4 text-3xl font-bold text-blue-600 uppercase"><%= quiz.title %></div>
									<span class="text-sm">
											Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptate tempore eligendi magnam
											distinctio molestias. Incidunt at consequuntur consequatur
											officiis repudiandae! Culpa cum tenetur itaque eius provident voluptatum similique impedit?
									</span>
							</div>

							<div class="px-10 py-1 mb-2 text-center">
								<span class="text-lg">
									<% quiz_presenter = ResultStatusPresenter.new(quiz: quiz, user: current_user) %>
									Status <%= quiz_presenter.status %>
								</span>
							</div>

							<% if quiz.theory %>
										<%= button_to "Let's Start", quiz_prepare_path(quiz), method: :get, class: "w-full h-16 text-lg font-extrabold text-gray-100 transition duration-300 bg-blue-500 rounded-b-lg hover:bg-purple-700 cursor-pointer" %>
							<% else %>

										<%= button_to "Let's Start", practice_index_path, method: :get, class: "w-full h-16 text-lg font-extrabold text-gray-100 transition duration-300 bg-blue-500 rounded-b-lg hover:bg-purple-700 cursor-pointer" %>
							<% end %>

					</div>
			</div>
		<% end %>
			<% else %>
				No Any Quizzes
			<% end %>
	</main>


<% else %>

<div class="login-wrapper">
	<%= form_for resource, as: resource_name, url: session_path(resource_name) do |f| %>
		<div class="field">
			<%= f.text_field :username, autofocus: true, required: true, placeholder: "Username" %>
		</div>

		<div class="field">
			<%= f.password_field :password, required: true, placeholder: "Password" %>
		</div>

		<% if devise_mapping.rememberable? %>
			<div class="checkbox-form-wrapper">
				<%= f.check_box :remember_me, class: 'regular-checkbox' %>
				<%= f.label :remember_me %>
			</div>
		<% end %>

		<div>
			<%= f.submit "Log in", class: 'actions' %>
		</div>
	<% end %>
<% end %>

</div>